apiVersion: v1
kind: Pod
metadata:
  name: sample-pull-secret
spec:
  containers:
    - name: secret-image-container
      image: sample-registry/secret-image:latest
  imagePullSecrets:
    - name: smaple-registry-auth